# -*- coding: utf-8 -*-
{
    "name": "Spa Staff Payroll",
    "version": "17.0.1.3.0",
    "category": "Human Resources",
    "summary": "Phiếu lương nhân viên Spa (dịch vụ theo buổi, làm thêm giờ, nghỉ)",
    "author": "Spa / booking_calendar integration",
    "license": "LGPL-3",
    'sequence': -100,
    "depends": [
        "spa",
        "booking_calendar",
        "sale",
        "account",
        "hr",
        "hr_contract",
        "mail",
    ],
    "data": [
        "security/spa_staff_payroll_security.xml",
        "security/spa_staff_payroll_rules.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/spa_payroll_default_tiers_data.xml",
        "views/hr_contract_views.xml",
        "views/spa_staff_dayoff_views.xml",
        "views/spa_staff_overtime_views.xml",
        "views/spa_staff_payroll_views.xml",
        "views/spa_staff_payroll_config_views.xml",
        "views/product_payroll_views.xml",
        "views/spa_booking_payroll_views.xml",
        "views/spa_session_payroll_views.xml",
        "views/spa_payroll_ranking_views.xml",
        "views/spa_staff_payroll_commission_report_views.xml",
        "views/res_config_settings_views.xml",
        "report/spa_staff_payroll_report.xml",
        "wizards/spa_staff_payroll_generate_wizard_views.xml",
        "views/hr_employee_hide_create_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
